### ISSUE TITLE
Doesn't `make` on OSX Sierra

### ISSUE THREAD

**Issue by ChristopherA** [ruda/jonesforth-macintel#1]
$ gcc -m32 -nostdlib -static jonesforth-macintel.s -o jonesforth
<instantiation>:9:9: error: non-local symbol required in directive
 .globl LT
        ^
jonesforth-macintel.s:220:2: note: while in macro instantiation
 defcode "<",1,0,LT,name_NEQU
 ^
<instantiation>:9:9: error: non-local symbol required in directive
 .globl LE
        ^
jonesforth-macintel.s:238:2: note: while in macro instantiation
 defcode "<=",2,0,LE,name_GT
 ^
<instantiation>:9:9: error: non-local symbol required in directive
 .globl LIT
        ^
jonesforth-macintel.s:327:2: note: while in macro instantiation
 defcode "LIT",3,0,LIT,name_EXIT
 ^
<instantiation>:9:9: error: non-local symbol required in directive
 .globl LATEST
        ^
<instantiation>:1:1: note: while in macro instantiation
defcode "LATEST",6,0,LATEST,name_HERE
^
jonesforth-macintel.s:402:2: note: while in macro instantiation
 defvar "LATEST",6,0,LATEST,name_HERE,name_SYSCALL
 ^
<instantiation>:9:9: error: non-local symbol required in directive
 .globl LBRAC
        ^
jonesforth-macintel.s:741:2: note: while in macro instantiation
 defcode "[",1,F_IMMED,LBRAC,name_COMMA
 ^
<instantiation>:9:9: error: non-local symbol required in directive
 .globl LITSTRING
        ^
jonesforth-macintel.s:798:2: note: while in macro instantiation
 defcode "LITSTRING",9,0,LITSTRING,name_ZBRANCH
 ^
$

**Comment by ChristopherA** [comment]
I have placed a $100 bounty on this at BountySource https://www.bountysource.com/issues/38256930-doesn-t-make-on-osx-sierra

**Comment by unidwell** [comment]
Hi, I issued a pull request to solve the observed issue. The error was the result of GNU Assembler interpreting all symbols starting with letter "L" as local.

**Comment by ChristopherA** [comment]
I can confirm that this pull request will close this issue https://github.com/ruda/jonesforth-macintel/pull/2

**Comment by unidwell** [comment]
Great :)
